#!/usr/bin/env node

/**
 * Build configuration file generation script
 * Generates config.js file using package.json version and current time.
 */

const fs = require('fs');
const path = require('path');

// Read version from package.json
const packageJsonPath = path.join(__dirname, '..', 'package.json');
let version = '1.0.0';

try {
  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
  version = packageJson.version || '1.0.0';
} catch (error) {
  console.warn('Warning: Could not read package.json, using default version');
}

// Use current time as build time
const buildTime = new Date().toISOString();

// Get Git commit hash (optional)
let gitHash = '';
try {
  const { execSync } = require('child_process');
  gitHash = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
} catch (error) {
  console.warn('Warning: Could not get git hash');
}

// Create configuration object
const config = {
  version: version,
  buildTime: buildTime,
  gitHash: gitHash,
  name: 'tools.h4o.kim',
  description: 'Miscellaneous web tools for daily use - JSON formatter, text counter, image converter, and more'
};

// Generate config.js file content
const configFileContent = `// This file is automatically generated during build.
// Do not edit manually.
// Generated at: ${buildTime}

export const APP_CONFIG = ${JSON.stringify(config, null, 2)};
`;

// Write to src/config.js file
const configFilePath = path.join(__dirname, '..', 'src', 'config.js');
fs.writeFileSync(configFilePath, configFileContent, 'utf8');

console.log(`✅ Config file generated successfully!`);
console.log(`   Version: ${version}`);
console.log(`   Build time: ${buildTime}`);
if (gitHash) {
  console.log(`   Git hash: ${gitHash}`);
}
console.log(`   File: ${configFilePath}`);
