#!/usr/bin/env node
import { writeFileSync } from 'fs';
import { execSync } from 'child_process';
import { readFileSync } from 'fs';

// Read package.json for version info
const packageJson = JSON.parse(readFileSync('./package.json', 'utf-8'));

// Get git hash if available
let gitHash = '';
try {
  gitHash = execSync('git rev-parse --short HEAD', { encoding: 'utf-8' }).trim();
} catch (error) {
  console.warn('Could not get git hash:', error.message);
}

// Generate build time
const buildTime = new Date().toISOString();

// Create config content
const configContent = `// This file is automatically generated during build.
// Do not edit manually.
// Generated at: ${buildTime}

export const APP_CONFIG = {
  "version": "${packageJson.version}",
  "buildTime": "${buildTime}",
  "gitHash": "${gitHash}",
  "name": "${packageJson.name === 'tools' ? 'tools.h4o.kim' : packageJson.name}",
  "description": "${packageJson.description || 'Miscellaneous web tools for daily use - JSON formatter, text counter, image converter, and more'}"
};
`;

// Write config file
writeFileSync('./src/config.js', configContent);
console.log('Generated src/config.js');